# Generated by Django 5.1.1 on 2024-09-12 21:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='name',
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
