# Generated by Django 5.1.1 on 2024-09-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.FloatField()),
                ('color', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
