services:
  web:
    image: adopt_a_pet
    container_name: adopt_a_pet
    build:
      context: ./adopt_a_pet
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=mysql
    ports:
      - "8000:8000"
    volumes:
      - ./adopt_a_pet:/app #/app tiene que ser igual a lo que le puse en el WORKDIR del Dockerfile
    depends_on:
      - mysql
      
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pet
    volumes:
      - mysql_data:/data/db
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
volumes:
  mysql_data:
